const axios = require("axios");

//This function uses Axios to call the SWSD API to POST a new incident
//The incident is assigned to the user whose email was passed in the "assigneeEmail" parameter

    function postChatIncident(assigneeEmail) {
    const BASE_URL = `https://api.samanage.com/incidents.xml`

    const Config = {
        headers: {
        "X-Samanage-Authorization": "Bearer TOKEN",
        "Accept": "application/xml",
        "Content-Type": "text/xml"
       },
    };

    const Data = {
        data: "<incident><name>ITService ChatBot Incident</name><priority>Critical</priority><requester><email>ITService@dpr.com</email></requester><category><name>General</name></category><description>This is a default incident generated by the ITSD chatbot. Please input the requisite information.</description><custom_fields_values><custom_fields_value><name>Origin</name><value>Chat</value></custom_fields_value></custom_fields_values></incident>"
    
    }

    const holdresponse = axios.post(BASE_URL, Data, Config)
    .then((response) => {
        console.log('Successfully made Chat POST Call');
      }, (error) => {
        console.log(error);
      });

    return holdresponse;
}


module.exports.postChatIncident = postChatIncident;
